openapi: 3.0.2
info:
  title: API docs
  description: >-
    ARPetPals is a mobile augmented reality (AR) application designed for
    Android. ARPetPals aims to aid users in their health and fitness journey in
    a fun and interactive way by integrating real-world activity tracking and
    object recognition, where user's daily movement and nutrition contribute to
    the health and happiness of their virtual pet, encouraging them to stay
    active and make healthier eating choices. ARPetPals allows users to adopt
    and interact with virtual pets in their real-world environments such as
    one’s desk at work. The virtual pet requires care, attention, and playtime,
    with their happiness and health metrics affected by user interactions. The
    game also leverages object recognition AI to enable virtual pets to interact
    with real-world objects, enhancing the gameplay experience. The health of
    the virtual pet is directly correlated with the user’s diet and activity
    habits. Using object recognition, the game will recognize food a user is
    eating and record the nutrition information. The healthier the food, the
    more nourished a pet becomes. The app will remind users to nourish their pet
    throughout the day and to interact with it by exercising. The pet will
    become more fit and content based on a user's activity level. There is an
    interactive aspect to the game where the health of a virtual pet is
    displayed on a public leader board. This gives users incentive to keep up
    their pets' health status by adding a competitive nature to the game. The
    game also uses speech to text AI to give commands and interact with the
    virtual pet. ARPetPals will be developed using the Unity 3D game engine,
    version 2022.2.21.
servers:
  - url: /api/
tags:
  - name: authentication
    externalDocs:
      description: API for logging in and logging out
paths:
  /api/signin:
    post:
      summary: Tries to sign in
      tags:
        - authentication
      requestBody:
        description: The username and password to sign in
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthSchema'
      responses:
        '200':
          description: Authentication was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSuccess'
  /api/signup:
    post:
      summary: Tries to sign up
      tags:
        - authentication
      requestBody:
        description: The username and password to sign up
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthSchema'
      responses:
        '200':
          description: Authentication was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSuccess'
components:
  schemas:
    AuthSchema:
      type: object
      properties:
        username:
          type: string
          description: the username to authenticate
        password:
          type: string
          description: the password to authenticate
    UserInfo:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    AuthSuccess:
      type: object
      properties:
        token:
          type: string
          description: the auth token
        userInfo:
          type: object
          schema:
            $ref: '#/components/schemas/UserInfo'
