openapi: 3.0.2
info:
  title: API docs
  description: >-
    ARPetPals is a mobile augmented reality (AR) application designed for
    Android. ARPetPals aims to aid users in their health and fitness journey in
    a fun and interactive way by integrating real-world activity tracking and
    object recognition, where user's daily movement and nutrition contribute to
    the health and happiness of their virtual pet, encouraging them to stay
    active and make healthier eating choices. ARPetPals allows users to adopt
    and interact with virtual pets in their real-world environments such as
    one’s desk at work. The virtual pet requires care, attention, and playtime,
    with their happiness and health metrics affected by user interactions. The
    game also leverages object recognition AI to enable virtual pets to interact
    with real-world objects, enhancing the gameplay experience. The health of
    the virtual pet is directly correlated with the user’s diet and activity
    habits. Using object recognition, the game will recognize food a user is
    eating and record the nutrition information. The healthier the food, the
    more nourished a pet becomes. The app will remind users to nourish their pet
    throughout the day and to interact with it by exercising. The pet will
    become more fit and content based on a user's activity level. There is an
    interactive aspect to the game where the health of a virtual pet is
    displayed on a public leader board. This gives users incentive to keep up
    their pets' health status by adding a competitive nature to the game. The
    game also uses speech to text AI to give commands and interact with the
    virtual pet. ARPetPals will be developed using the Unity 3D game engine,
    version 2022.2.21.
servers:
  - url: /api/v3
tags:
  - name: object-recognition
    description: Describes the object-recognition from the AR Foundational API
    externalDocs:
      description: Find out more about AR Foundational API
      url: >-
        https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@6.0/manual/features/features.html
  - name: display
    externalDocs:
      description: API for displaying pets using Unity technology
paths:
  /display/renderPet:
    post:
      summary: Renders the pet using Unity.
      operationId: renderPet
      tags:
        - display
      requestBody:
        description: Pet details to be rendered.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetDetails'
      responses:
        '200':
          description: Pet rendered successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderResponse'
  /display/configureDisplay:
    post:
      summary: Configures display settings for Unity.
      operationId: configureDisplay
      tags:
        - display
      requestBody:
        description: Display settings and parameters.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisplayConfiguration'
      responses:
        '200':
          description: Display configured successfully.
  /display/manageUserDisplay:
    post:
      summary: Manages the display of the pet and other elements on the screen.
      operationId: manageUserDisplay
      tags:
        - display
      requestBody:
        description: Details for managing user display.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDisplayRequest'
      responses:
        '200':
          description: User display managed successfully.
  /object-recogntion/ARTrackedImageManager:
    get:
      tags:
        - object-recognition
      summary: ARTrackedImageManager
      description: >-
        Describes API used in order to track images, which performs 2D image
        tracking.
  /object-recogntion/ARTrackedObjectManager:
    get:
      tags:
        - object-recognition
      summary: ARTrackedObjectManager
      description: Describes API used in order to track real-world 3D objects
  /object-recogntion/ARHumanBodyManager:
    get:
      tags:
        - object-recognition
      summary: ARHumanBodyManager
      description: Describes API used in order to track  human bodies in an AR scene.
  /object-recogntion/ARPlaneManager:
    get:
      tags:
        - object-recognition
      summary: ARPlaneManager
      description: >-
        Describes API used in order to track real-world planes ( real world
        surfaces like desks, floors,etc)
components:
  schemas:
    PetDetails:
      type: object
      properties:
        petId:
          type: string
          description: ID of the pet to be rendered.
        petModelPath:
          type: string
          description: Path to the Unity model of the pet.
        additionalParameters:
          type: object
          description: Additional parameters for rendering.
    DisplayConfiguration:
      type: object
      properties:
        resolution:
          type: string
          description: Resolution for the display.
        quality:
          type: string
          description: Quality settings for the display.
        fullscreen:
          type: boolean
          description: Whether to use fullscreen mode.
    UserDisplayRequest:
      type: object
      properties:
        petId:
          type: string
          description: ID of the pet to be displayed.
        showPet:
          type: boolean
          description: Whether to show or hide the pet.
        additionalElements:
          type: array
          description: Other elements to display on the screen.
          items:
            type: string
    RenderResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the rendering.
        message:
          type: string
          description: Any additional messages from the renderer.
